---
version: '2'
services:

  splunk:
    image: splunk/splunk:latest
    container_name: splunk
    user: root
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=Password1
      - SPLUNK_APPS_URL=./splunkapps/cwd-splunk-app.tgz,./splunkapps/wordcloud-custom-visualization_111.tgz
    ports:
      - 8000:8000
      - 8088:8088
    volumes:
      - ./default.yml:/tmp/defaults/default.yml

