repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-yaml
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-symlinks
      - id: check-docstring-first
      - id: end-of-file-fixer
      - id: debug-statements

  - repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
      - id: black
        name: Black code formatting
